### ISSUE TITLE
Failed to parse color map

### ISSUE THREAD

**Issue by Yv-vY** [red-data-tools/red-colors#18]
As per https://bugs.ruby-lang.org/issues/18167 the red-colors fails to register colors and prevents to run any application using the red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb .

Sample output (trying to run a Gtk 3 app with Ruby 3.0.2 on Fedora 34):

```text
/home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:989:in `block in <module:ColormapRegistry>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:973:in `each'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:973:in `<module:ColormapRegistry>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:2:in `<module:Colors>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb:1:in `<top (required)>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data.rb:24:in `require_relative'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data.rb:24:in `<module:ColormapRegistry>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data.rb:5:in `<module:Colors>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data.rb:4:in `<top (required)>'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors.rb:42:in `require_relative'
	from /home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors.rb:42:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/.gem/ruby/3.0.2/gems/cairo-1.17.5/lib/cairo/color.rb:1:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/.gem/ruby/3.0.2/gems/cairo-1.17.5/lib/cairo.rb:47:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/.gem/ruby/3.0.2/gems/cairo-gobject-3.4.9/lib/cairo-gobject.rb:17:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/.gem/ruby/3.0.2/gems/gdk3-3.4.9/lib/gdk3.rb:18:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/.gem/ruby/3.0.2/gems/gtk3-3.4.9/lib/gtk3.rb:18:in `<top (required)>'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from /home/yann/devel/facts/app/facts_app.rb:8:in `<main>'
<internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gtk3 (LoadError)
	from <internal:/opt/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/yann/devel/facts/app/facts_app.rb:8:in `<main>'
```

A workaround - until Ruby JSON module is fixed - would be to use JSON.parse instead of JSON.load in the colormap_data.rb / load_colormap_data() method.

Note: I don't know how this behaves on other systems / environments but I believe that it's quite a general bug under this configuration (Ruby, gem, etc.).

**Comment by kou** [comment]
Could you attach your `/home/yann/.gem/ruby/3.0.2/gems/red-colors-0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb`?

It seems that it's different from https://github.com/red-data-tools/red-colors/blob/0.3.0/lib/colors/colormap_data/matplotlib_builtin.rb .

**Comment by Yv-vY** [comment]
I've found the cause of the issue: my script loads the `oj` gem and calls `Oj.mimic_JSON` prior to requiring Gtk3.
This indeed lead to this error and it seems that `oj` `load()` method doesn't behave identically as the standard library JSON.

I'll report the issue to the `oj` gem maintainer.

Sorry to have barked at the wrong tree ;)
